// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQpiwTrXSY_yL1zmX85eUNqo7Y315BSk',
    appId: '1:207379885957:web:12bae6fa7ae399d4e75eec',
    messagingSenderId: '207379885957',
    projectId: 'tutorapp-fb110',
    authDomain: 'tutorapp-fb110.firebaseapp.com',
    storageBucket: 'tutorapp-fb110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXlX2fFSz1rCnbi3GI4dEBPlqUAPfphso',
    appId: '1:207379885957:ios:be1ab946305f0b0ae75eec',
    messagingSenderId: '207379885957',
    projectId: 'tutorapp-fb110',
    storageBucket: 'tutorapp-fb110.appspot.com',
    iosBundleId: 'com.example.tutorApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFhlFZcaXgN7nDJTh66e7kOOSc6oAwnmk',
    appId: '1:207379885957:android:fbb14bcf674c8966e75eec',
    messagingSenderId: '207379885957',
    projectId: 'tutorapp-fb110',
    storageBucket: 'tutorapp-fb110.appspot.com',
  );
}
